/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef STARTAPP_AUTODEFS_H
#define STARTAPP_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_STARTAPP_NAME "startapp"
#define S3E_EXT_STARTAPP_HASH 0x693e0874

#endif /* !STARTAPP_AUTODEFS_H */
